# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-13 01:14
from __future__ import unicode_literals

import core.utils.uploads
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(db_index=True, max_length=255, unique=True, verbose_name='Email Address')),
                ('first_name', models.CharField(blank=True, max_length=40, null=True, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=40, null=True, verbose_name='last name')),
                ('display_name', models.CharField(blank=True, max_length=14, null=True, verbose_name='display name')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this users should be treated as active. Unselect this instead of deleting profiles.', verbose_name='Active')),
                ('date_joined', models.DateTimeField(auto_now=True, verbose_name='date joined')),
                ('is_admin', models.BooleanField(default=False, verbose_name='Is_admin')),
            ],
            options={
                'verbose_name': 'user',
                'db_table': 'auth_user',
                'swappable': 'customer.User',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('date_created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='date created')),
                ('date_modified', models.DateTimeField(auto_now=True, null=True, verbose_name='date modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(default=False, editable=False)),
                ('document_type', models.CharField(blank=True, choices=[('', '--Choose--'), ('ID-01', 'DNI'), ('ID-02', 'RUC'), ('ID-03', 'PASSPORT')], max_length=20, null=True)),
                ('document_number', models.CharField(blank=True, max_length=20, null=True)),
                ('cell', models.CharField(blank=True, max_length=20, null=True)),
                ('initial_date', models.DateField(auto_now=True, null=True)),
                ('final_date', models.DateField(blank=True, default='', null=True)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to=core.utils.uploads.upload_location_profile)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer_userprofile_company', to='core.Company')),
                ('country', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer_userprofile_country', to='core.Country')),
                ('state', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer_userprofile_country', to='core.State')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='customer_userprofile_user', to=settings.AUTH_USER_MODEL)),
                ('zone', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer_userprofile_zone', to='core.Zone')),
            ],
            options={
                'db_table': 'user_profile',
                'ordering': ['date_created'],
            },
            managers=[
                ('current', django.db.models.manager.Manager()),
            ],
        ),
    ]
