# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-13 01:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('taxonomy', '0001_initial'),
        ('container', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tripmammal',
            name='mammal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='container_tripmammal_mammal', to='taxonomy.Mammal'),
        ),
        migrations.AddField(
            model_name='tripmammal',
            name='trip_detail_final',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='container_tripmammal_trip_mammal_final', to='container.Trip'),
        ),
        migrations.AddField(
            model_name='tripmammal',
            name='trip_detail_initial',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='container_tripmammal_trip_mammal_initial', to='container.Trip'),
        ),
        migrations.AddField(
            model_name='trip',
            name='container',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='container_trip_container', to='container.Container'),
        ),
        migrations.AddField(
            model_name='fisher',
            name='company',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='container_fisher_company', to='core.Company'),
        ),
        migrations.AddField(
            model_name='container',
            name='country',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='container_container_country', to='core.Country'),
        ),
        migrations.AddField(
            model_name='container',
            name='fisher',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='container_container_fisher', to='container.Fisher'),
        ),
        migrations.AddField(
            model_name='container',
            name='port',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='container_container_port', to='core.Port'),
        ),
        migrations.AddField(
            model_name='container',
            name='zone',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='container_container_zone', to='core.Zone'),
        ),
        migrations.AlterUniqueTogether(
            name='container',
            unique_together=set([('identifier_mac',)]),
        ),
    ]
