# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-16 13:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('container', '0002_auto_20160613_0114'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='name',
        ),
    ]
