# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-13 01:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classification',
            fields=[
                ('date_created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='date created')),
                ('date_modified', models.DateTimeField(auto_now=True, null=True, verbose_name='date modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(default=False, editable=False)),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('name_tax', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'verbose_name_plural': '3. classifications',
                'ordering': ['date_created'],
            },
            managers=[
                ('current', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Family',
            fields=[
                ('date_created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='date created')),
                ('date_modified', models.DateTimeField(auto_now=True, null=True, verbose_name='date modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(default=False, editable=False)),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('name_tax', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'verbose_name_plural': '5. familys',
                'ordering': ['date_created'],
            },
            managers=[
                ('current', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='FamilySpecie',
            fields=[
                ('date_created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='date created')),
                ('date_modified', models.DateTimeField(auto_now=True, null=True, verbose_name='date modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(default=False, editable=False)),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('name_tax', models.CharField(blank=True, max_length=50, null=True)),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taxonomy_familyspecie_family', to='taxonomy.Family')),
            ],
            options={
                'ordering': ['date_created'],
            },
            managers=[
                ('current', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Kingdom',
            fields=[
                ('date_created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='date created')),
                ('date_modified', models.DateTimeField(auto_now=True, null=True, verbose_name='date modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(default=False, editable=False)),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('name_tax', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'verbose_name_plural': '1. kingdoms',
                'ordering': ['date_created'],
            },
            managers=[
                ('current', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Mammal',
            fields=[
                ('date_created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='date created')),
                ('date_modified', models.DateTimeField(auto_now=True, null=True, verbose_name='date modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(default=False, editable=False)),
                ('classification', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='taxonomy_mammal_classification', to='taxonomy.Classification')),
                ('family', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='taxonomy_mammal_family', to='taxonomy.Family')),
                ('group', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='taxonomy_mammal_group', to='menu.GroupState')),
                ('kingdom', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='taxonomy_mammal_kingdom', to='taxonomy.Kingdom')),
            ],
            options={
                'ordering': ['date_created'],
            },
            managers=[
                ('current', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('date_created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='date created')),
                ('date_modified', models.DateTimeField(auto_now=True, null=True, verbose_name='date modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(default=False, editable=False)),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('name_tax', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'verbose_name_plural': '4. orders',
                'ordering': ['date_created'],
            },
            managers=[
                ('current', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='SubType',
            fields=[
                ('date_created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='date created')),
                ('date_modified', models.DateTimeField(auto_now=True, null=True, verbose_name='date modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(default=False, editable=False)),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('name_tax', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'ordering': ['date_created'],
            },
            managers=[
                ('current', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('date_created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='date created')),
                ('date_modified', models.DateTimeField(auto_now=True, null=True, verbose_name='date modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(default=False, editable=False)),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('name_tax', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'verbose_name_plural': '2. types',
                'ordering': ['date_created'],
            },
            managers=[
                ('current', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='type',
            unique_together=set([('name',)]),
        ),
        migrations.AddField(
            model_name='subtype',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taxonomy_subtype_type', to='taxonomy.Type'),
        ),
        migrations.AlterUniqueTogether(
            name='order',
            unique_together=set([('name',)]),
        ),
        migrations.AddField(
            model_name='mammal',
            name='order',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='taxonomy_mammal_order', to='taxonomy.Order'),
        ),
        migrations.AddField(
            model_name='mammal',
            name='specie',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='taxonomy_mammal_specie', to='taxonomy.FamilySpecie'),
        ),
        migrations.AddField(
            model_name='mammal',
            name='subtype',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='taxonomy_mammal_subtype', to='taxonomy.SubType'),
        ),
        migrations.AddField(
            model_name='mammal',
            name='type',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='taxonomy_mammal_type', to='taxonomy.Type'),
        ),
        migrations.AlterUniqueTogether(
            name='kingdom',
            unique_together=set([('name',)]),
        ),
        migrations.AddField(
            model_name='family',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taxonomy_family_order', to='taxonomy.Order'),
        ),
        migrations.AlterUniqueTogether(
            name='classification',
            unique_together=set([('name',)]),
        ),
        migrations.AlterUniqueTogether(
            name='subtype',
            unique_together=set([('name',)]),
        ),
        migrations.AlterUniqueTogether(
            name='mammal',
            unique_together=set([('order', 'family', 'specie', 'group')]),
        ),
        migrations.AlterUniqueTogether(
            name='familyspecie',
            unique_together=set([('name',)]),
        ),
        migrations.AlterUniqueTogether(
            name='family',
            unique_together=set([('order', 'name')]),
        ),
    ]
